### ISSUE TITLE
Integrate with gatsby-source-cloudinary

### ISSUE THREAD

**Issue by maoznir** [cloudinary-devs/gatsby-transformer-cloudinary#14]
Currently this plugin uploads local images to cloudinary.
Assets that are already in the user's Cloudinary media library isn't handled. To solve this, can act on nodes created by gatsby-source-cloudinary. This will require making sure from time to time that the selection of which nodes to act on is aligned with how gatsby-source-cloudinary names the nodes it creates.

**Comment by hazzyeer** [comment]
Still waiting for this enhancement ...

**Comment by rshackleton** [comment]
Arguably the `gatsby-source-cloudinary` and `gatsby-transformer-cloudinary` should be combined into one, and updated for `gatsby@3` & `gatsby-plugin-image`. 🤔

**Comment by cloudinary-raae** [comment]
Released: v3.0.0
