### ISSUE TITLE
Add upload options like create_derived=true/false

### ISSUE THREAD

**Issue by maoznir** [cloudinary-devs/gatsby-transformer-cloudinary#15]
Should let the user define options in gatsby-config.js that will affect uploading.
for example: create_derived=false to cloudinary.v2.uploader.upload() function, will make sure that the plugin does not create tens of transformations for each image.

**Comment by Chuloo** [comment]
This enhancement was done in #21, and this issue will be closed. Please re-open if you have any further queries regarding the enhancement.

**Comment by amcc** [comment]
We have a library of about 11,000 images that are being added in gatsby-node using exports.sourceNodes
each image then gets added with createRemoteFileNode

This successfully uploads everything to cloudinary. The issue we're having is that it does this on every build and is burning through a lot of transformations each time. All our images are now uploaded, so its simply going through existing images each time and is doing new transformations.

I've tried setting createDerived to false, in the last build it created 43,300 transformations on 11226 images.

How do we prevent Cloudinary doing new transformations on images it already has?
