### ISSUE TITLE
Initiate global state in a Gatsby v4 compatible way

### ISSUE THREAD

**Issue by raae** [cloudinary-devs/gatsby-transformer-cloudinary#157]
Keep backward compatibility to v3.

- [ ] [Follow docs](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/#3-global-state)

Part of #139

**Comment by olavea** [comment]
✋

**Comment by cloudinary-raae** [comment]
Released: v2.3.0
