### ISSUE TITLE
Not able to query Cloudinary Assets

### ISSUE THREAD

**Issue by tpiros** [cloudinary-devs/gatsby-transformer-cloudinary#18]
I have setup the `gatsby-transformer-cloudinary` plugin as per the docs.

Using the GraphQL playground (`localhost:8000/__graphql`) I am not able to query any of the images (and consequently, I don't see the results in my app either):

```
{
  file(name: {eq: "winter-jumper"}) {
    cloudinary: childCloudinaryAsset {
      fluid {
        src
      }
    }
  }
}
```

The above returns

```
{
  "data": {
    "file": null
  }
}
```

Even though I can confirm that an image with the public ID specified above exists, in the folder that I have added in the configuration (see below).

`gatsby.config.js`:

```
require('dotenv').config({
  path: `.env.development`,
});

module.exports = {
  plugins: [
  // other plugins ... ,
  {
    resolve: `gatsby-source-filesystem`,
    options: {
      name: `images`,
      path: `${__dirname}/src/images`,
    },
    {
      resolve: `gatsby-transformer-cloudinary`,
      options: {
        cloudName: process.env.CLOUDINARY_CLOUD_NAME,
        apiKey: process.env.CLOUDINARY_API_KEY,
        apiSecret: process.env.CLOUDINARY_API_SECRET,
        uploadFolder: `jamstack-training`,
      },
    },
  ]
};
```

**Comment by Chuloo** [comment]
Hi, @tpiros can you confirm if this still an issue? Also, query all the CloudinaryAssets in GraphQL to see if any file nodes were created.

**Comment by Chuloo** [comment]
Hi @tpiros, for this, can you specify the folder in the gatsby-source-filesystem before the config for the plugin?

```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/jamstack-training`, // path to folder
      },
    },
```
