### ISSUE TITLE
Validate configured options using `pluginOptionsSchema`

### ISSUE THREAD

**Issue by raae** [cloudinary-devs/gatsby-transformer-cloudinary#186]
Relevant Gatsby Docs
- https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/configuring-usage-with-plugin-options

**Comment by olavea** [comment]
✋

**Comment by olavea** [comment]
[https://github.com/raae/gatsby-transformer-cloudinary/pull/8#pullrequestreview-1120251123](https://github.com/raae/gatsby-transformer-cloudinary/pull/8#pullrequestreview-1120251123)
