### ISSUE TITLE
Remove support for deprecated gatsby-image

### ISSUE THREAD

**Issue by raae** [cloudinary-devs/gatsby-transformer-cloudinary#188]

**Comment by olavea** [comment]
✋

**Comment by olavea** [comment]
Maybe this is done?
Have a look:
[https://github.com/raae/gatsby-transformer-cloudinary/pull/8#pullrequestreview-1120251123](https://github.com/raae/gatsby-transformer-cloudinary/pull/8#pullrequestreview-1120251123)
