### ISSUE TITLE
Rework demo

### ISSUE THREAD

**Issue by raae** [cloudinary-devs/gatsby-transformer-cloudinary#190]
So it's easier for folks to run and test the demo, and it's not connected to a person they might not know:
- [x] Use Unsplash photos
  - Replace all Jason/Marisa images with unsplash photos
  - Download medium size
- [x] Replace beard transformation with one that is easily replicable
  - Makes it easier for folks to add the transformation to their account when testing the demo
- [x] Use gatsby-plugin-image terminology
  - Ie. remove fixed/fluid categorization

**Comment by olavea** [comment]
✅ 😸 🏴‍☠️
