### ISSUE TITLE
Error [ValidationError]: "error" must be of type object

### ISSUE THREAD

**Issue by nmampersand** [cloudinary-devs/gatsby-transformer-cloudinary#214]
Hello! I am working on a project using Gatsby, Cloudinary, and Sanity and am running into the error with this plugin:

```
Failed to validate error [Error [ValidationError]: "error" must be of type object] {
  _original: {
    context: {
      sourceMessage: '[gatsby-transformer-cloudinary] Could not get metadata for undefined > undefined: undefined'
    },
    error: 'Unknown cloud_name',
    pluginName: 'gatsby-transformer-cloudinary',
    text: '[gatsby-transformer-cloudinary] Could not get metadata for undefined > undefined: undefined',
    level: 'ERROR',
    stack: [],
    docsUrl: 'https://gatsby.dev/issue-how-to'
  },
  details: [
    {
      message: '"error" must be of type object',
      path: [Array],
      type: 'object.base',
      context: [Object]
    }
  ]
}
```
I am only using images already in Cloudinary but have tried configuring it with and without my Cloudinary credentials and receive the same error.

My gatsby-config looks like:

```
plugins: [
...,
{
    resolve: 'gatsby-source-filesystem',
    options: {
      name: `images`,
      path: `${__dirname}/src/images/`
    },
  }, {
    resolve: `gatsby-source-cloudinary`,
    options: {
      cloudName: process.env.CLOUDINARY_CLOUD_NAME,
      apiKey: process.env.CLOUDINARY_API_KEY,
      apiSecret: process.env.CLOUDINARY_API_SECRET,
    },
  }, {
    resolve: 'gatsby-transformer-cloudinary',
    options: {
      cloudName: process.env.CLOUDINARY_CLOUD_NAME,
      apiKey: process.env.CLOUDINARY_API_KEY,
      apiSecret: process.env.CLOUDINARY_API_SECRET,
      transformTypes: [
        `CloudinaryMedia`,
        `CloudinaryAsset`,
        `SanityCloudinaryAsset`
      ],
    },
  }]
```

**Comment by nmampersand** [comment]
Note: when I do provide the Cloudinary config options to the plugin and run `gatsby develop`, it does successfully upload my local images to Cloudinary but still throws the above error.

**Comment by raae** [comment]
That is not a great error message, so we'll make sure to fix that.

However it seems that your `SanityCloudinaryAsset` GraphQL type does not have the required fields. It needs at least the fields: `publicId` and a `cloudName`.

Could you go to your GraphiQL UI (typically http://localhost:8000/___graphql) and check the shape of `SanityCloudinaryAsset`?

**Comment by nmampersand** [comment]
Thank you! Hmm, it looks like it doesn't have a cloud name:

```
    {
          "name": "SanityCloudinaryAsset",
          "fields": [
            {
              "name": "_key"
            },
            {
              "name": "_type"
            },
            {
              "name": "public_id"
            },
            {
              "name": "resource_type"
            },
            {
              "name": "type"
            },
            {
              "name": "format"
            },
            {
              "name": "version"
            },
            {
              "name": "url"
            },
            {
              "name": "secure_url"
            },
            {
              "name": "width"
            },
            {
              "name": "height"
            },
            {
              "name": "bytes"
            },
            {
              "name": "duration"
            },
            {
              "name": "tags"
            },
            {
              "name": "created_at"
            },
            {
              "name": "derived"
            },
            {
              "name": "access_mode"
            },
            {
              "name": "_rawDerived"
            }
          ]
        }
```

**Comment by raae** [comment]
And the data is not in the shape required by this plugin (something I hope to make configurable in the future). You'll have to make your own nodes base on these nodes. I can give you an example of how to achieve this tomorrow (CET timezone).

**Comment by nmampersand** [comment]
That would be great, thank you!

**Comment by raae** [comment]
I made an question and answered it here: #215 and keeping this issue to reference when fixing the not optimal error message.

**Comment by raae** [comment]
I would be forever grateful if you tested the newest beta [nmampersand ](https://github.com/nmampersand ). It adds support for Sanity sourced Cloudinary assets by letting you configure the mapping of data.

`yarn add gatsby-transformer-cloudinary@4.6.0-beta.1`

Take a look at [the documentation](https://www.npmjs.com/package/gatsby-transformer-cloudinary/v/4.6.0-beta.1) and let me know how it goes so I may improve if needed.

**Comment by raae** [comment]
@nmampersand, have you been able to test the 4.6.0-beta.1? Looking to make this a current version, but would love an external test before I do.
