### ISSUE TITLE
warning [gatsby-transformer-cloudinary] No metadata for ... gatsbyImageData will resolve to null

### ISSUE THREAD

**Issue by amcc** [cloudinary-devs/gatsby-transformer-cloudinary#239]
It is possible to suppress these warnings. For a site we're building we're getting over 3000 warnings like this which sometimes seems to be causing the build to fail.

Checking a few of the culprits. They're videos, or other non-image files, so nothing is wrong really.

using gatsby@5.9.1 and gatsby-transformer-cloudinary@4.4.0

**Comment by raae** [comment]
Sure, I'll look into making them only appear with the verbose flag, maybe. Or be able to turn them off.

**Comment by amcc** [comment]
Thanks!

**Comment by raae** [comment]
Added logLevel to the resolver so one can do: 
```
          gatsbyImageData(
            height: 200
            backgroundColor: "#BADA55"
            logLevel: "error"
          )
