### ISSUE TITLE
"apiKey" is a required plugin option

### ISSUE THREAD

**Issue by vlknhslk** [cloudinary-devs/gatsby-transformer-cloudinary#60]
I was using the plugin for a while but I've been getting a trouble since yesterday. `gatsby develop` is running but when I run `gatsby build` command, I am getting this error below.

`[gatsby-transformer-cloudinary] "apiKey" is a required plugin option. You can add it to the options object for "gatsby-transformer-cloudinary" in your gatsby-config file.`

**Comment by kurttomlinson** [comment]
Have you added your Cloudinary API key to your config? Here's the documentation showing how to do that: https://github.com/cloudinary-devs/gatsby-transformer-cloudinary/blob/master/packages/gatsby-transformer-cloudinary/README.md#configure-the-plugin

**Comment by Chuloo** [comment]
Closing this out now as there hasn't been any follow-up. Please feel free to comment/re-open if the issue still exists 🙏
