### ISSUE TITLE
specify allowed paths, owners or types

### ISSUE THREAD

**Issue by joernroeder** [cloudinary-devs/gatsby-transformer-cloudinary#71]
I'm currently combining the cloudinary transformer with several other source and transformer plugins and I am having a hard time limiting the scope of files which should be uploaded to cloudinary.  For example the transformer currently picks up images inside the `.cache` directory, which makes it impossible to use it with other plugins which cache their remote files.
Being able to include/exclude files by their path owner or type would help.

I'm happy to submit a pull request to allow limiting source path.

**Comment by Chuloo** [comment]
Hi @joernroeder I think this makes sense to limit the source path, I would love to see what the architecture is like, care to send a PR and we can review it?

**Comment by joernroeder** [comment]
@Chuloo sure, I'll set something up next week.

**Comment by cloudinary-raae** [comment]
Released: v2.3.0
