### ISSUE TITLE
How to upload client local image to cloudinary

### ISSUE THREAD

**Issue by lemurweb-dev** [cloudinary-devs/gatsby-transformer-cloudinary#76]
Heii i was wondering how could i upload an image from the client local pc (through a form file input) to cloudinary and then get the URL of that image in return.
Is it possible?

**Comment by Chuloo** [comment]
@lemurweb-dev is this a Gatsby project? or a plain React.js project?

**Comment by lemurweb-dev** [comment]
@Chuloo  it's for a gatsby project

**Comment by Chuloo** [comment]
Great! With a custom form, I assume you want to handle the upload yourself and manage the returned URL after. You can explore triggering the Cloudinary Upload widget from your image upload button. You can find info on the React integration here https://cloudinary.com/documentation/react_image_and_video_upload

You also could look at the Cloudinary upload API to handle this. You can see the docs here:
https://cloudinary.com/documentation/image_upload_api_reference

Lastly, if you'd like to upload local images and add these URLs to Gatsby's data layer and query it in GraphQL then you can utilize the gatsby-transformer-cloudinary plugin.

**Comment by Chuloo** [comment]
Closing this out now, let me know if you have any further questions on using Cloudinary in your Gatsby project :)
