### ISSUE TITLE
Integration with gatsby-source-graphql

### ISSUE THREAD

**Issue by hazzyeer** [cloudinary-devs/gatsby-transformer-cloudinary#77]
Hello,
When using the plugin `gatsby-source-graphql` and calling data from it, It seems that the `gatsby-transfomer-cloudinary` plugin don't recognize coming objects with the structure:
```
{
  ...,
  coverPhoto: {
      cloudinaryAssetData: true,
      cloudName: "my-amazing-blog",
      publicId: "blue-blue-blue",
      originalHeight: 360,
      originalWidth: 820
  }
}
```
to automatically fetch images from Cloudinary, and have a node of type CouldinaryAsset as described [here](https://www.npmjs.com/package/gatsby-transformer-cloudinary#use-images-already-on-cloudinary).
The only thing that I can do as query is the following:
```
query Data {
  pos {
    products {
      coverPhoto {
        alt
        cloudName
        cloudinaryAssetData
        originalWidth
        originalHeight
        publicId
      }
    }
  }
}
```

**Comment by Chuloo** [comment]
Hi @hazzyeer, I'm a bit off on what you want to achieve :). Could you provide more context, probably with an ideal graphql query you're trying to make?
