### ISSUE TITLE
Yarn Install

### ISSUE THREAD

**Issue by doakheggeness** [cloudinary-devs/gatsby-transformer-cloudinary#8]
I have created yarn workspaces from scratch, but I am having trouble with this one. I cloned your repo & I created a Cloudinary account and input my settings in the .env file & I ran yarn install from the root, which I thought would install all dependencies and and got the following....

$ yarn workspaces info
yarn workspaces v1.17.3
{
  "gatsby-transformer-cloudinary": {
    "location": "packages/gatsby-transformer-cloudinary",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  },
  "site": {
    "location": "site",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": [
      "gatsby-transformer-cloudinary"
    ]
  }
}
Done in 0.06s.

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome

I appreciate your work on this, it looks like the future!

**Comment by jlengstorf** [comment]
Maybe try `yarn workspace site add "gatsby-transformer-cloudinary@*"` — that _should_ pick up the local package and resolve the mismatched dependency.

**Comment by Chuloo** [comment]
has this been resolved for you? @doakheggeness ?

**Comment by doakheggeness** [comment]
Yes, thanks Sent from Mail for Windows 10 From: WilliamSent: Tuesday, December 24, 2019 3:19 PMTo: cloudinary-devs/gatsby-transformer-cloudinaryCc: Doak Heggeness; MentionSubject: Re: [cloudinary-devs/gatsby-transformer-cloudinary] Yarn Install (#8) has this been resolved for you? @doakheggeness ?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Chuloo** [comment]
Great to see all is solved for you @doakheggeness 👍
