### ISSUE TITLE
Include original Cloudinary JSON data after transformer has run

### ISSUE THREAD

**Issue by rshackleton** [cloudinary-devs/gatsby-transformer-cloudinary#89]
The current implementation of the transformer completely replaces the Cloudinary JSON data with the new `CloudinaryAsset` GQL type.

It would be useful to still have the option of accessing some of the original properties - particularly the public_id field - if we wish to do some manual transformation via the Cloudinary SDK.

**Comment by raae** [comment]
Would it be interesting to have a `rawCloudinaryData` field, that includes everything returned by Cloudinary when uploading?

**Comment by rshackleton** [comment]
I've not used Gatsby in a while but I'd expect the more data available, the better.

**Comment by cloudinary-raae** [comment]
Released: v2.3.0
