### ISSUE TITLE
Api key required

### ISSUE THREAD

**Issue by popeating** [cloudinary-devs/gatsby-transformer-cloudinary#93]
Documentation states:

_The options cloudName, apiKey, and apiSecret are required if any images will be uploaded to Cloudinary during the build process. If you're solely using images already uploaded to Cloudinary, then these options can be safely omitted._

But if i remove one of these option (i don't need upload, since my files are already on cloudinary)  i got the following error when running gatsby develop:

`[gatsby-transformer-cloudinary] "apiKey" is a required plugin option. You can add it to the options object for "gatsby-transformer-cloudinary" in your gatsby-config file.`

also leaving the values blank leads to errors, so it looks like the plugin cant be used with images already stored on cloudinary without uploading;

it works only by disabling  _gatsby-source-filesystem_ image section, but i cant do it since im using the local images for other things;

a "no-upload" option would be really useful

**Comment by Chuloo** [comment]
Currently investigating this

**Comment by Chuloo** [comment]
I'm currently able to reproduce this, looking for a process that calls the `uploadImageToCloudinary` function which triggers this error.
